baseline:
  description: "baseline medium"
  bounds:
    EX_cpd00011_e0: 10.0
    EX_cpd00007_e0: 1000.0
    EX_cpd00001_e0: 1000.0

low_co2:
  description: "reduced CO2 uptake bound"
  bounds:
    EX_cpd00011_e0: 2.0
    EX_cpd00007_e0: 1000.0
    EX_cpd00001_e0: 1000.0

low_oxygen:
  description: "reduced oxygen uptake bound"
  bounds:
    EX_cpd00011_e0: 10.0
    EX_cpd00007_e0: 2.0
    EX_cpd00001_e0: 1000.0

high_co2:
  description: "increased CO2 uptake bound"
  bounds:
    EX_cpd00011_e0: 20.0
    EX_cpd00007_e0: 1000.0
    EX_cpd00001_e0: 1000.0

low_water:
  description: "reduced water uptake bound"
  bounds:
    EX_cpd00011_e0: 10.0
    EX_cpd00007_e0: 1000.0
    EX_cpd00001_e0: 2.0
